// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ8XSqOTG5Cuvo7QGmvDy99MKvIIg8xFA',
    appId: '1:991362307957:web:e6c9a1f1377a1d94c9e53c',
    messagingSenderId: '991362307957',
    projectId: 'igo123',
    authDomain: 'igo123.firebaseapp.com',
    storageBucket: 'igo123.firebasestorage.app',
    measurementId: 'G-KBH8NB15C0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKsunWOwCRUo2OUFWChI2Mq7yDOJWzCck',
    appId: '1:991362307957:android:0b6a7a1eacaabe31c9e53c',
    messagingSenderId: '991362307957',
    projectId: 'igo123',
    storageBucket: 'igo123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8XGNN1TKXXZucBxrdLHxdUju5v-jF6ec',
    appId: '1:991362307957:ios:ce07c8240e042be7c9e53c',
    messagingSenderId: '991362307957',
    projectId: 'igo123',
    storageBucket: 'igo123.firebasestorage.app',
    iosClientId: '991362307957-gcfpjba4gg3j5odurg93v8l3e6kak5ba.apps.googleusercontent.com',
    iosBundleId: 'com.example.igo123',
  );

}